apiVersion: v1
kind: ConfigMap
metadata:
  name: imageimport-api
data:
  environment : "Test"
  swaggerSettings.useSwaggerUI: "true"
  importSettings.AllowedCorsOrigins: "https://localhost,https://louvre.test-elvia.io"