apiVersion: apps/v1
kind: Deployment
metadata:
  name: kunde-tariff-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: kunde-tariff-api
  template:
    metadata:
      labels:
        app: kunde-tariff-api
    spec:
      serviceAccountName: kunde-tariff-api
      imagePullSecrets:
      - name: containerregistryprodsecret
      dnsConfig:
        options:
        - name: single-request-reopen
      containers:
      - name: kunde-tariff-api
        image: containerregistryelvia.azurecr.io/kunde-tariff-api:imagetag
        resources:
          requests:
            cpu: "300m"
            memory: "500Mi"
          limits:
            cpu: "500m"
            memory: "2Gi"
        startupProbe:
          httpGet:
            path: /ping
            port: 80
          failureThreshold: 40
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: 80
          periodSeconds: 30
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "15"]
        env:
          - name: SwaggerSettings__UseSwaggerUI
            valueFrom:
              configMapKeyRef:
                name: kunde-tariff-api
                key: swaggerSettings.useSwaggerUI
          - name: SwaggerSettings__PathPrefix
            value: "/tariff-api"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kunde-tariff-api
  name: kunde-tariff-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: kunde-tariff-api-port
#    targetport: 8080
  selector:
    app: kunde-tariff-api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kunde-tariff-api
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
    kubernetes.io/ingress.class: traefik
    # Redirect the /metrics endpoint to /
    # This ensures that the /metrics endpoint is not open on the internet
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    traefik.ingress.kubernetes.io/request-modifier: "ReplacePathRegex: ^/metrics(.*) /"
spec:
  rules:
  - host: kunde.:domaintag
    http: 
      paths:
      - path: /tariff-api
        backend:
          serviceName: kunde-tariff-api
          servicePort: 80
---
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  # Prometheus will scrape metrics on the http endpoint, kunde-tariff-api-port
  name: kunde-tariff-api
  namespace: kunde
spec:
  endpoints:
  - port: kunde-tariff-api-port
    interval: 5s
  selector:
    matchLabels:
      app: kunde-tariff-api
