---
trigger:
  - "*"

pool:
  vmImage: "ubuntu-latest"

variables:
  containerregistry: "ContainerRegistryElvia"
  imagetag: $(Build.BuildNumber)
  name: grid-tariff-api
  namespace: kunde

resources:
  repositories:
    - repository: templates
      type: github
      name: 3lvia/core-azure-devops-templates
      endpoint: 3lvia

stages:
  - stage: Build
    jobs:
      - template: test.yaml@templates
        parameters:
          unitTestProjects: |
            **/*Tests/*.csproj
      - template: build.yaml@templates
        parameters:
          dockerfile: Dockerfile

  - stage: DeployDev
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/trunk'), true)
    dependsOn: Build
    jobs:
      - template: deploy.yaml@templates
        parameters:
          environment: dev
          helmValuesFile: values.yaml

  - stage: DeployTest
    dependsOn: DeployDev
    jobs:
      - template: deploy.yaml@templates
        parameters:
          environment: test
          helmValuesFile: values.yaml

  - stage: RegisterAzureApiManagementTest
    dependsOn: DeployTest
    jobs:
    - job: CreateOrUpdateProduct
      pool:
        vmImage: "windows-latest"
      steps:
        - task: stephane-eyskens.apim.apimcreateorupdateproduct.apimcreateorupdateproduct@3
          displayName: 'API Management - Create/Update Product '
          inputs:
            ConnectedServiceNameARM: ApiManagementRGTest
            ResourceGroupName: 'API-RGtest'
            ApiPortalName: elviatest
            product: 'grid-tariff'
            DisplayName: 'Grid Tariff'
            subscriptionRequired: true
            approvalRequired: true
            state: true
            groups: |
                Administrators
                Developers
                Guests
        - task: stephane-eyskens.apim.apim.apim@3
          displayName: 'API Management - Create/Update API '
          inputs:
            ConnectedServiceNameARM: ApiManagementRGTest
            ResourceGroupName: 'API-RGtest'
            ApiPortalName: elviatest
            UseProductCreatedByPreviousTask: true
            OpenAPISpec: v3
            swaggerlocation: 'https://grid-tariff-api.test-elvia.io/swagger/v1/swagger.json'
            targetapi: gridtariffapi
            DisplayName: GridTariffApi
            pathapi: 'grid-tariff'
            TemplateSelector: Custom
            Custom: |
             <policies>
                 <inbound>
                     <base />
                     <authentication-basic username="$(grid-tariff-api-username-test)" password="$(grid-tariff-api-password-test)" />
                     <rate-limit-by-key calls="1200" renewal-period="60"
                     increment-condition="@((context.Response.StatusCode &gt;= 200) &amp;&amp; (context.Response.StatusCode &lt; 300))"
                     counter-key="@(context.Subscription.Key)" />					  
                 </inbound>
                 <backend>
                     <base />
                 </backend>
                 <outbound>
                     <base />
                 </outbound>
                 <on-error>
                     <base />
                 </on-error>
             </policies>
            MicrosoftApiManagementAPIVersion: '2018-01-01'

  - stage: DeployProd
    dependsOn: RegisterAzureApiManagementTest
    jobs:
      - template: deploy.yaml@templates
        parameters:
          environment: prod
          helmValuesFile: values.yaml
