# Default values for elvia-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: grid-tariff-api
namespace: kunde
microserviceType: webapi

replicaCount: 1

image:
  repository: containerregistryelvia.azurecr.io/kunde-grid-tariff-api

resources:
  requests:
    cpu: "500m"
    memory: "500Mi"
  limits:
    cpu: "1"
    memory: "2Gi"

env:
 - name: mdmx__host-address
   valueFrom:
     configMapKeyRef:
       name: grid-tariff-api
       key: mdmx.host-address

service:
  port: 80
  targetPort: 8080

ingress:
  subdomain: grid-tariff-api
  path: "/"
  
configmap:
  dev:
    mdmx.host-address: https://mdmx.dev-elvia.io/
#    bigtable.project: "hafslund-mdm-dev"
#    bigtable.instanceid: "mdm-meterreadings-dev"
  test:
    mdmx.host-address: https://mdmx.test-elvia.io/
#    bigtable.project: "hafslund-mdm-test"
#    bigtable.instanceid: "mdm-meterreadings-test"
  prod:
    mdmx.host-address: https://mdmx.elvia.io/
#    bigtable.project: "hafslund-mdm"
#    bigtable.instanceid: "mdm-meterreadings"
