# Default values for elvia-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: grid-tariff-api
namespace: kunde
microserviceType: webapi

replicaCount: 1

image:
  repository: containerregistryelvia.azurecr.io/kunde-grid-tariff-api

resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "150m"
    memory: "1Gi"

#env:
#  - name: ELVID__Authority
#    valueFrom:
#      configMapKeyRef:
#        name: pushreceiver-profiledmeterreadings
#        key: elvid.authority
#  - name: ELVID__RequiredScope
#    value: pr.sesam
#  - name: bigtable__project
#    valueFrom:
#      configMapKeyRef:
#        name: pushreceiver-profiledmeterreadings
#        key: bigtable.project
#  - name: bigtable__instanceid
#    valueFrom:
#      configMapKeyRef:
#        name: pushreceiver-profiledmeterreadings
#        key: bigtable.instanceid

service:
  port: 80
  targetPort: 8080

ingress:
  subdomain: kunde
  path: "/grid-tariff-api"
  
#configmap:
#  dev:
#    kvalitetsportalen.environment: DEV
#    elvid.authority: https://elvid.test-elvia.io/
#    bigtable.project: "hafslund-mdm-dev"
#    bigtable.instanceid: "mdm-meterreadings-dev"
#  test:
#    kvalitetsportalen.environment: AMS-T01
#    elvid.authority: https://elvid.test-elvia.io/
#    bigtable.project: "hafslund-mdm-test"
#    bigtable.instanceid: "mdm-meterreadings-test"
#  prod:
#    kvalitetsportalen.environment: HIPAD
#    elvid.authority: https://elvid.elvia.io/
#    bigtable.project: "hafslund-mdm"
#    bigtable.instanceid: "mdm-meterreadings"
