# Default values for elvia-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: grid-tariff-api
namespace: kunde
microserviceType: webapi

replicaCount:
  dev: 1
  test: 1
  prod: 2

image:
  repository: containerregistryelvia.azurecr.io/kunde-grid-tariff-api

resources:
  requests:
    cpu: "1"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "3Gi"

env:
 - name: mdmx__host-address
   valueFrom:
     configMapKeyRef:
       name: grid-tariff-api
       key: mdmx.host-address
 - name: mdmx__access-token-service-config-vault-path
   valueFrom:
     configMapKeyRef:
       name: grid-tariff-api
       key: mdmx.access-token-service-config-vault-path

service:
  port: 80
  targetPort: 8080

ingress:
  subdomain: grid-tariff-api
  path: "/"
 
 # Syncing of data from bigquery to database  can make the startup take a long time
startupProbe:
  failureThreshold: 125
  httpGet:
    path: /ping
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 3

readinessProbe:
  failureThreshold: 125
  httpGet:
    path: /ping
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 3

livenessProbe:
  failureThreshold: 125
  httpGet:
    path: /ping
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 3
  
configmap:
  dev:
    mdmx.host-address: https://mdmx.dev-elvia.io/
    mdmx.access-token-service-config-vault-path: kunde:kv:elvid:kunde-grid-tariff-api
  test:
    mdmx.host-address: https://mdmx.test-elvia.io/
    mdmx.access-token-service-config-vault-path: kunde:kv:elvid:kunde-grid-tariff-api
  prod:
    mdmx.host-address: https://mdmx.test-elvia.io/
    mdmx.access-token-service-config-vault-path: kunde:kv:manual:kunde-grid-tariff-api-test
