# Default values for elvia-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: grid-tariff-api-synchronizer
namespace: kunde
microserviceType: webapi

replicaCount:
  dev: 1
  test: 1
  prod: 1

image:
  repository: containerregistryelvia.azurecr.io/kunde-grid-tariff-api

resources:
  requests:
    cpu: "1"
    memory: "500Mi"
  limits:
    cpu: "3"
    memory: "3Gi"

env:
 - name: deployment-role
   value: synchronizer
 - name: mdmx__host-address
   value: MDMx host address not set up for synchronizer deployment
 - name: mdmx__access-token-service-config-vault-path
   value: kunde:kv:elvid:kunde-grid-tariff-api

service:
  port: 80
  targetPort: 8080

startupProbe:
  failureThreshold: 60
  httpGet:
    path: /ping
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 2
  periodSeconds: 2
  successThreshold: 1
  timeoutSeconds: 1

# Large synchronizations might take a long time - allow for unresponsiveness for about half an hour
readinessProbe:
 failureThreshold: 120
 httpGet:
   path: /ping
   port: 8080
   scheme: HTTP
 initialDelaySeconds: 15
 periodSeconds: 15
 successThreshold: 1
 timeoutSeconds: 3

livenessProbe:
 failureThreshold: 120
 httpGet:
   path: /ping
   port: 8080
   scheme: HTTP
 initialDelaySeconds: 15
 periodSeconds: 15
 successThreshold: 1
 timeoutSeconds: 3
